### ISSUE TITLE
switch from h5py to pytables

### ISSUE THREAD

**Issue by maitchison** [TheCacophonyProject/classifier-pipeline#16]
We use H5PY as the backend for the track database, however, it does not support blosc compression.  

To work around this we are importing a specific version of pytables which installs the blosc compression filter and then using it in h5py.  This workaround breaks easily and does not work on our Linux machines.  For this reason, blosc compression has been disabled.

To enabled blosc compression reliability we will need to switch over the track database IO from h5py to pytables.  These libraries both use HD5F so they should work interchangeably.  

All of the trackdatabase IO is abstracted in the class TrackDatabase found in trackdatabase.py 

Because the track extractor uses multiple processes some care will be needed to make sure that two processes do not write to the same file at the same time.  Currently a locking system is used, however, an alternative would be to modify the track extractor to use a dedicated process to write the frames.

**Comment by mjs** [comment]
Instead of switching to pytables, do #59 instead.
