### ISSUE TITLE
hdf5_lock is a lower-cased global object

### ISSUE THREAD

**Issue by timClicks** [TheCacophonyProject/classifier-pipeline#21]
As a newcomer to the code, it's hard to tell where the `hdf5_lock` is instantiated:
 
```python
class HDF5Manager:
    """ Class to handle locking of HDF5 files. """
    def __init__(self, db, mode = 'r'):
        self.mode = mode
        self.f = None
        self.db = db

    def __enter__(self):
        # note: we might not have to lock when in read only mode?
        # this could improve performance
        hdf5_lock.acquire()                                              # <---- ?
        self.f = h5py.File(self.db, self.mode)
        return self.f

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.f.close()
        hdf5_lock.release()                                              # <---- ?
```

After having a hunt, it turns out to be a [sentinel global](https://github.com/TheCacophonyProject/classifier-pipeline/blob/e3cf35449755b09dd85bfc0979de5df8bc1cce55/ml_tools/trackdatabase.py#L251) at the bottom of the file. Perhaps replace with an ALL CAPS variable name and instantiate the lock nearby to where it's being used?

**Comment by mjs** [comment]
Fixed in #22.  See also #16.
